# Base ESPHome configuration for all devices.
# Includes essential components for Home Assistant integration, connectivity, and device management.
#
# REQUIRED SUBSTITUTIONS:
#   device_name        : The internal device name for ESPHome (e.g., bedroom_lights, kitchen_plug).
#   friendly_name      : The human-readable device name (e.g., Bedroom Lights, Kitchen Plug).
#   device_description : A description of the device (e.g., Magic Home Wifi RGB LED Controller).

packages:
  - !include ha_api_secure.yaml
  - !include debug.yaml
  - !include logger.yaml
  - !include wifi.yaml
  - !include time.yaml
  - !include ota.yaml
  - !include restart_button.yaml
  - !include uptime_sensor.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
