packages:
  - !include ha_api_secure.yaml
  - !include debug.yaml
  - !include logger.yaml
  - !include wifi.yaml
  - !include time.yaml
  - !include ota.yaml
  - !include restart_button.yaml
  - !include uptime_sensor.yaml
