# Base ESPHome configuration for all devices.
# Requires substitutions: device_name, friendly_name, device_description

packages:
  - !include ha_api_secure.yaml
  - !include debug.yaml
  - !include logger.yaml
  - !include wifi.yaml
  - !include time.yaml
  - !include ota.yaml
  - !include restart_button.yaml
  - !include uptime_sensor.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: ${device_description}
