packages:
  - !include logger.yaml # debug platform requires logger to be enabled

debug:
  update_interval: 3min

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Last Reset Reason"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    cpu_frequency:
      name: "CPU Frequency"
