packages:
  # Standard HA time sync (defaults to basic API).
  # To enable encryption, include `ha_api_secure.yaml` in your main config alongside this package.
  # ESPHome's merge logic will ensure the secure config overrides this basic one.
  - !include ha_api_basic.yaml

# Synchronize time from Home Assistant
time:
  - platform: homeassistant
    id: ha_time
