packages:
  - !include common/magichome_rgb_led_controller.yaml

substitutions:
  device_name: bed-lights
  friendly_name: Bed Lights
  device_description: Magic Home Wifi ZJ-WFMN-A V1.1 RGB LED Controller
