packages:
  - !include common/magichome_rgb_led_controller.yaml

substitutions:
  device_name: mh1
  device_description: Magic Home Wifi ESP-IR-B-v2.3 RGB LED Controller
  friendly_name: Shelf Lights
