packages:
  - !include components/base.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: Daybetter FLSL501115WIFITY RGB LED Strip (BK7231T)

bk72xx:
  board: generic-bk7231t-qfn32-tuya
