packages:
  - !include components/base.yaml

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: Daybetter FLSL501115WIFITY RGB LED Strip (BK7231T)

bk72xx:
  board: generic-bk7231t-qfn32-tuya

output:
  - platform: libretiny_pwm
    id: output_red
    pin: P6
    frequency: 1000 Hz

  - platform: libretiny_pwm
    id: output_green
    pin: P7
    frequency: 1000 Hz

  - platform: libretiny_pwm
    id: output_blue
    pin: P8
    frequency: 1000 Hz

light:
  - platform: rgb
    name: "Daybetter LED Strip"
    id: light_rgb
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: RESTORE_DEFAULT_OFF
