packages:
  - !include components/base.yaml
  - !include components/rgb_ir_remote.yaml

# For rgb_ir_remote
substitutions:
  ir_receiver_pin: P16
  light_id: leds

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: Daybetter FLSL501115WIFITY RGB LED Strip (BK7231T)

bk72xx:
  board: generic-bk7231t-qfn32-tuya

output:
  - platform: libretiny_pwm
    id: output_red
    pin: P7
    frequency: 1000 Hz
  - platform: libretiny_pwm
    id: output_green
    pin: P8
    frequency: 1000 Hz
  - platform: libretiny_pwm
    id: output_blue
    pin: P6
    frequency: 1000 Hz

light:
  - platform: rgb
    name: Controller
    id: ${light_id}
    red: output_red
    green: output_green
    blue: output_blue
    restore_mode: RESTORE_DEFAULT_OFF
